In [ ]:
import torch
import pandas as pd
import numpy as np
from collections import Counter

In [8]:
df = pd.read_csv("../data/fake_behavior.csv")
df.tail(2)

,t_dat,customer_id,article_id,event_type
2123499,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,582480024,click
2123500,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,751288001,click

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2123501 entries, 0 to 2123500
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   t_dat        object
 1   customer_id  object
 2   article_id   int64
 3   event_type   object
dtypes: int64(1), object(3)
memory usage: 64.8+ MB

In [ ]:
def build_graph(df, session_gap_days=7):
    df = df.copy()
    df["t_dat"] = pd.to_datetime(df["t_dat"])

    edges = []
    count = 0
    for user, user_df in df.groupby("customer_id"):
        user_df = user_df.sort_values("t_dat")

        items = user_df["article_id"].tolist()
        times = user_df["t_dat"].tolist()

        if len(items) < 2:
            continue

        session = [items[0]]
        print(f"user: {user[:8]}, {len(user_df)}")
        print(session)
        count+=1
        if count==5:
            break
        for i in range(1, len(items)):
            gap = (times[i] - times[i-1]).days

            if gap <= session_gap_days:
                session.append(items[i])
            else:
                edges += build_session_edges(session)
                session = [items[i]]
        edges += build_session_edges(session)

    # 🔥 COUNT WEIGHT
    edge_counter = Counter(edges)
    print(f"edge counter: {edge_counter}")

    all_items = set([a for (a, b) in edge_counter.keys()] + 
                    [b for (a, b) in edge_counter.keys()])

    id2idx = {aid: i for i, aid in enumerate(all_items)}

    edge_index = []
    edge_weight = []

    for (a, b), w in edge_counter.items():
        edge_index.append([id2idx[a], id2idx[b]])
        edge_weight.append(w)

    edge_index = torch.tensor(edge_index, dtype=torch.long).t()
    edge_weight = torch.tensor(edge_weight, dtype=torch.float)

    print("Num nodes:", len(id2idx))
    print("Num edges:", edge_index.shape[1])

    return edge_index, edge_weight, id2idx


def build_session_edges(session):
    edges = []
    for i in range(len(session)):
        for j in range(i + 1, len(session)):
            a, b = session[i], session[j]
            edges.append((a, b))
            edges.append((b, a))
    return edges

In [6]:
transactions_path = "../data/transactions_train.csv"
df = pd.read_csv(transactions_path)
df["article_id"] = df["article_id"].astype(str).str.zfill(10)
df.head(5)

,t_dat,customer_id,article_id,price,sales_channel_id
0,2020-08-09,0004df3751c43c51f79aa24d321f35ce4a1a3ec180c4a1...,0832482001,0.016932,1
1,2020-08-09,0004df3751c43c51f79aa24d321f35ce4a1a3ec180c4a1...,0802881001,0.067780,1
2,2020-08-09,0004df3751c43c51f79aa24d321f35ce4a1a3ec180c4a1...,0783707047,0.005068,1
3,2020-08-09,000fb6e772c5d0023892065e659963da90b1866035558e...,0852585002,0.042356,2
4,2020-08-09,000fb6e772c5d0023892065e659963da90b1866035558e...,0852585002,0.042356,2

In [21]:
build_graph(df)

user: 00006413, 4
['0896152002']
user: 00009d94, 4
['0884319008']
user: 0001d44d, 8
['0900157002']
user: 00025f82, 3
['0781613016']
user: 0003e867, 3
['0927358001']
edge counter: Counter({('0900157002', '0900157002'): 2, ('0900157002', '0850244001'): 2, ('0850244001', '0900157002'): 2, ('0900157002', '0850244002'): 2, ('0850244002', '0900157002'): 2, ('0900157002', '0850244003'): 2, ('0850244003', '0900157002'): 2, ('0900157002', '0820484002'): 2, ('0820484002', '0900157002'): 2, ('0900157002', '0820484004'): 2, ('0820484004', '0900157002'): 2, ('0900157002', '0812818003'): 2, ('0812818003', '0900157002'): 2, ('0896152002', '0730683050'): 1, ('0730683050', '0896152002'): 1, ('0896152002', '0927530004'): 1, ('0927530004', '0896152002'): 1, ('0896152002', '0791587015'): 1, ('0791587015', '0896152002'): 1, ('0730683050', '0927530004'): 1, ('0927530004', '0730683050'): 1, ('0730683050', '0791587015'): 1, ('0791587015', '0730683050'): 1, ('0927530004', '0791587015'): 1, ('0791587015', '0927530004'): 1, ('0884319008', '0921226001'): 1, ('0921226001', '0884319008'): 1, ('0884319008', '0706016001'): 1, ('0706016001', '0884319008'): 1, ('0884319008', '0881244001'): 1, ('0881244001', '0884319008'): 1, ('0921226001', '0706016001'): 1, ('0706016001', '0921226001'): 1, ('0921226001', '0881244001'): 1, ('0881244001', '0921226001'): 1, ('0706016001', '0881244001'): 1, ('0881244001', '0706016001'): 1, ('0850244001', '0850244002'): 1, ('0850244002', '0850244001'): 1, ('0850244001', '0850244003'): 1, ('0850244003', '0850244001'): 1, ('0850244001', '0820484002'): 1, ('0820484002', '0850244001'): 1, ('0850244001', '0820484004'): 1, ('0820484004', '0850244001'): 1, ('0850244001', '0812818003'): 1, ('0812818003', '0850244001'): 1, ('0850244002', '0850244003'): 1, ('0850244003', '0850244002'): 1, ('0850244002', '0820484002'): 1, ('0820484002', '0850244002'): 1, ('0850244002', '0820484004'): 1, ('0820484004', '0850244002'): 1, ('0850244002', '0812818003'): 1, ('0812818003', '0850244002'): 1, ('0850244003', '0820484002'): 1, ('0820484002', '0850244003'): 1, ('0850244003', '0820484004'): 1, ('0820484004', '0850244003'): 1, ('0850244003', '0812818003'): 1, ('0812818003', '0850244003'): 1, ('0820484002', '0820484004'): 1, ('0820484004', '0820484002'): 1, ('0820484002', '0812818003'): 1, ('0812818003', '0820484002'): 1, ('0820484004', '0812818003'): 1, ('0812818003', '0820484004'): 1, ('0781613016', '0781613006'): 1, ('0781613006', '0781613016'): 1, ('0781613016', '0751471001'): 1, ('0751471001', '0781613016'): 1, ('0781613006', '0751471001'): 1, ('0751471001', '0781613006'): 1})

In [10]:
filtered_df = df[df["t_dat"] == "2020-08-14"]
print(f"Số dòng với t_dat = 2020-08-14: {len(filtered_df)}")
filtered_df.head(10)

Số dòng với t_dat = 2020-08-14: 184758

,t_dat,customer_id,article_id,event_type
49,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,884319008,purchase
50,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,858052007,click
51,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,921226001,purchase
52,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,832282001,click
53,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,706016001,purchase
54,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,836364002,click
55,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,881244001,purchase
56,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,766402020,click
133,2020-08-14,00025f8226be50dcab09402a2cacd520a99e112fe01fdd...,781613016,purchase
134,2020-08-14,00025f8226be50dcab09402a2cacd520a99e112fe01fdd...,823791002,click

In [29]:
hist_df = df[df["t_dat"] != "2020-08-14"]
print(f"Số dòng với t_dat: {len(hist_df)}")
hist_df.head(5)
hist_df.to_csv("../data/hist_data.csv", index=False)

Số dòng với t_dat: 1938743

In [11]:
filtered_df.to_csv("../data/test.csv", index=False)

In [24]:
clip_data = torch.load("../data/clip_embeddings.pt")
data = torch.load("../data/article_embeddings_hgnn3.pt")

In [25]:
emb = data["embeddings"]
id2idx = data["id2idx"]

In [22]:
# In ra keys và 1 mẫu
print("Số keys:", len(clip_data.keys()))
print("\nCác keys (10 mẫu đầu):")
for i, key in enumerate(list(clip_data.keys())[:10]):
    print(f"  {key}")

# In ra 1 mẫu value
print("\n1 mẫu key-value:")
sample_key = list(clip_data.keys())[0]
print(f"Key: {sample_key}")
print(f"Value type: {type(clip_data[sample_key])}")
print(f"Value shape: {clip_data[sample_key].shape if hasattr(clip_data[sample_key], 'shape') else 'N/A'}")
print(f"Value: {clip_data[sample_key]}")

Số keys: 19284

Các keys (10 mẫu đầu):
  0108775044
  0111565001
  0111586001
  0111593001
  0111609001
  0120129001
  0120129014
  0123173001
  0126589007
  0126589010

1 mẫu key-value:
Key: 0108775044
Value type: <class 'torch.Tensor'>
Value shape: torch.Size([512])
Value: tensor([ 4.7273e-02,  6.4621e-02, -1.2524e-02,  2.1046e-02,  2.2154e-03,
        -3.0189e-02, -2.2084e-02, -5.6870e-03,  3.4435e-02, -1.1891e-02,
        -2.8226e-02, -6.4788e-02, -3.5684e-02, -2.2390e-03,  2.1674e-02,
         1.3855e-02, -7.1584e-02, -2.0553e-02, -2.9776e-03, -2.2854e-02,
        -1.4183e-02, -2.2618e-02, -3.4741e-02,  3.4026e-03, -2.5158e-02,
        -4.1193e-02, -1.3493e-03,  5.8652e-02, -4.0569e-02,  2.8711e-02,
        -8.1253e-02, -1.1579e-03,  3.0341e-02,  2.9245e-04,  5.1088e-03,
         1.9867e-02, -4.7859e-02,  1.3294e-02,  3.7160e-02, -1.0182e-02,
        -1.4246e-02, -4.5982e-02,  2.5034e-02,  2.5450e-02, -5.4300e-02,
        -4.3354e-03, -4.3745e-02,  8.7598e-03, -9.7880e-03, -6.5527e-02,
        -2.8249e-02,  5.7382e-03, -2.5044e-02, -1.2539e-02, -3.3429e-02,
        -3.2271e-02, -5.2022e-02,  3.2451e-02,  1.6054e-02,  4.8084e-02,
        -9.9582e-02, -1.6054e-02,  2.8460e-02,  1.0227e-02,  4.6081e-02,
         4.9168e-02, -9.3935e-03,  1.8662e-02, -1.0570e-02,  1.9698e-03,
        -4.1214e-02, -1.2973e-03,  2.5207e-02,  2.7342e-02,  3.5676e-03,
        -1.4736e-03, -1.6382e-02,  6.1713e-02,  2.2065e-02, -1.4755e-02,
         2.0637e-02, -1.1422e-01, -4.8607e-02,  1.5328e-02,  3.2096e-02,
        -2.0434e-02,  2.3566e-02, -3.7018e-02,  1.4521e-02,  3.2356e-02,
        -1.6344e-02, -1.6618e-02, -2.2110e-02, -3.2948e-02, -4.6250e-02,
         2.4127e-02,  1.3620e-02, -2.6113e-02, -2.3717e-03,  1.4003e-02,
        -2.9902e-02,  6.1171e-02,  2.7812e-02, -3.6003e-02,  3.4957e-02,
         1.2833e-02, -3.3083e-02,  7.3849e-02,  3.1052e-02, -2.9945e-02,
        -3.6074e-02, -4.2761e-02, -5.0092e-02,  3.0738e-02,  5.1401e-02,
        -2.4051e-02,  3.3642e-02,  2.1257e-02, -2.3379e-02, -4.7883e-02,
         4.0453e-02,  1.2276e-02, -2.0715e-03,  6.1697e-03,  3.8325e-02,
        -6.8611e-03, -1.8148e-02, -1.7492e-02,  3.0692e-02,  6.3290e-02,
         6.1724e-02, -1.6575e-02,  1.0453e-02, -3.7307e-03, -1.2519e-02,
         9.4385e-03,  3.4313e-03,  1.1920e-02,  1.2339e-02,  5.3392e-02,
        -4.6427e-02,  1.5901e-02, -3.7670e-02, -7.6734e-04, -3.1346e-02,
         2.9174e-02, -2.7170e-02,  2.5819e-02, -2.8835e-02,  3.8658e-02,
        -1.6384e-02,  3.4566e-02,  3.5345e-01,  6.8398e-03, -2.5627e-02,
        -3.5923e-03,  6.7303e-03,  2.3199e-02,  1.4993e-02, -2.4692e-02,
        -4.5554e-03,  8.0603e-03, -3.6400e-02, -4.1305e-03, -8.5985e-03,
         6.6260e-02, -1.0116e-02,  1.5586e-02, -8.9635e-03, -9.4170e-03,
         2.0586e-02,  1.7073e-02, -7.5377e-03, -1.2165e-02, -1.1172e-03,
        -7.6030e-02,  4.8404e-02,  1.3481e-02, -8.6734e-02,  4.6940e-02,
         3.5354e-03, -3.6833e-02, -5.1257e-02, -1.2893e-02, -1.5812e-02,
         5.5679e-02,  1.1232e-01,  1.7560e-02, -1.7718e-02, -1.8359e-02,
        -4.5410e-02,  9.8588e-02,  8.8622e-02, -2.9621e-02,  3.8494e-03,
         2.1592e-02,  1.1600e-02,  3.1252e-03,  8.2703e-03, -5.9865e-03,
         1.4157e-01, -3.6345e-03, -1.9528e-03,  1.1038e-02,  8.2352e-03,
        -1.8960e-02,  2.6038e-02,  1.8597e-02,  1.3507e-02, -5.4668e-02,
         5.0221e-04, -5.7912e-02,  3.9474e-03,  7.8636e-03,  2.0520e-02,
         3.9584e-02, -4.1713e-02,  3.4550e-02, -2.3889e-02, -5.1613e-02,
        -9.1643e-03, -2.7534e-02,  2.7599e-02,  1.6474e-02,  1.1639e-02,
         4.2523e-03,  2.6949e-02, -2.1286e-02, -1.6548e-02, -1.6375e-02,
         1.7748e-03,  1.1711e-02, -3.2483e-02,  1.6784e-02, -1.4083e-02,
        -2.6068e-02, -1.2276e-02, -5.2300e-02, -8.7486e-03, -2.6678e-02,
        -2.8290e-02,  5.2352e-02, -8.9756e-03,  1.3106e-02,  4.7504e-02,
        -5.1158e-02, -1.8066e-02,  3.5304e-02,  4.5284e-02,  8.8893e-03,
        -4.5115e-02,  3.7027e-02, -2.7628e-02, -4.1223e-02, -8.4922e-02,
        -2.9199e-02, -5.8286e-02,  4.0917e-02, -4.5540e-02, -4.5339e-02,
        -1.7071e-02, -1.1504e-02, -1.2347e-02, -2.0552e-02, -2.7557e-02,
         1.9934e-02, -4.4930e-02, -5.6006e-03, -1.5026e-02, -6.6788e-02,
        -1.6978e-02, -1.3957e-02,  3.6475e-02,  2.2365e-02, -2.8808e-02,
         1.7676e-02, -3.8072e-02, -2.8502e-02, -1.0988e-03, -5.5054e-02,
        -6.8351e-04,  4.5657e-02,  2.9888e-02,  4.0446e-02, -1.4955e-02,
        -1.9961e-02,  4.4162e-03, -1.2104e-02,  7.5830e-03,  2.2737e-02,
        -3.6066e-02,  9.6349e-03,  3.4923e-02, -2.3564e-02,  3.5289e-03,
         3.5678e-02,  2.1013e-03, -6.3108e-03,  1.2661e-04,  3.6983e-03,
         1.6632e-01, -1.0168e-01,  3.5649e-02,  7.2865e-02,  1.0206e-02,
         2.7388e-02, -2.2574e-02, -3.5284e-01, -1.5724e-02, -1.3066e-03,
        -5.5366e-02, -1.9356e-02,  3.7723e-02, -2.4249e-02,  3.7981e-02,
        -1.2201e-02,  1.6517e-02, -3.4466e-02,  3.8634e-02, -2.0910e-02,
        -3.8459e-02,  5.3663e-03,  1.3633e-03,  8.1241e-02, -1.3143e-01,
         3.5020e-02, -8.3347e-03,  4.6832e-02, -1.0374e-01, -1.2705e-03,
         3.7814e-03,  1.9279e-03,  2.2348e-02,  1.8263e-02,  2.3985e-02,
        -1.6758e-02, -2.5484e-02, -9.4327e-03, -4.5829e-03, -8.3647e-03,
         1.5527e-02,  2.1075e-02,  5.6878e-02, -3.8330e-02,  5.3516e-02,
        -4.9517e-02,  6.3860e-02, -2.4130e-03, -1.3097e-01, -2.2732e-02,
         4.2081e-02, -2.7033e-02, -1.9302e-02,  3.8798e-03, -4.1915e-02,
         4.5081e-02, -7.4899e-03,  5.0596e-02, -1.1388e-02,  6.1698e-02,
         5.7847e-03,  6.5392e-02,  7.7434e-03, -1.3216e-02, -2.9693e-02,
        -1.9295e-03,  5.8345e-04,  7.4444e-02,  3.4201e-02,  1.9067e-02,
         1.3328e-02, -3.0352e-02, -3.1965e-02,  1.7543e-03, -3.7887e-02,
         7.3755e-02,  4.3031e-02, -2.8812e-02, -2.1686e-02, -3.9332e-02,
         4.4800e-02,  1.9527e-02, -2.4608e-02, -4.1114e-02, -3.1807e-02,
         4.7047e-02, -1.2920e-02, -4.3235e-02,  6.8941e-02,  2.3907e-03,
        -3.9140e-02, -8.9302e-03,  4.8751e-02,  5.9705e-02,  2.2827e-02,
        -1.9006e-02,  9.5589e-02, -9.1641e-03,  5.5255e-03,  1.3120e-02,
         1.8190e-02, -1.3740e-02, -4.4248e-02,  6.9297e-02, -3.5971e-02,
         7.7513e-03,  1.4280e-02,  8.0167e-03, -1.1594e-02,  2.5209e-02,
         3.1609e-02,  4.0921e-02,  1.1560e-02,  3.4764e-02, -4.1356e-02,
        -5.8147e-04, -4.3922e-02,  1.2833e-02,  1.3773e-02, -2.3248e-02,
         2.1798e-02, -3.9339e-02, -3.4265e-02, -3.2434e-03,  5.8983e-02,
         6.2642e-02, -9.3181e-03,  5.1617e-02, -1.9031e-02,  1.0090e-02,
        -1.0273e-02,  2.0022e-01, -2.8820e-03,  2.2391e-02, -1.8934e-02,
        -1.9587e-02,  1.2193e-02,  8.7569e-03,  6.7577e-03,  2.2539e-03,
        -9.0388e-03, -4.1979e-02, -1.5064e-02, -1.6516e-02, -1.2076e-02,
        -7.4488e-03, -1.8049e-02, -1.7837e-02,  3.7833e-02,  2.1014e-02,
         2.0443e-03, -9.1907e-03, -2.7401e-02, -1.7027e-02, -7.0090e-02,
        -4.6460e-02, -6.1366e-02, -5.2938e-02, -4.1815e-02, -1.6022e-02,
        -1.0849e-02, -4.4581e-02, -1.8285e-02, -9.4238e-03, -1.1764e-02,
        -3.5989e-02,  2.5338e-02, -1.0943e-02, -2.8128e-02, -5.0921e-03,
        -1.0187e-01, -1.1761e-02, -1.5658e-02,  3.2264e-02, -1.0157e-02,
         4.2473e-02, -1.2849e-03,  6.1486e-02,  5.4782e-02, -3.6930e-05,
        -1.2186e-02, -5.1867e-03, -5.5966e-02, -9.3977e-02, -1.3691e-02,
        -4.5960e-02, -4.0212e-02,  1.0216e-03, -6.1329e-02,  4.5028e-03,
        -1.4942e-01, -2.7111e-03, -4.5754e-02,  2.8534e-02,  5.9950e-02,
         4.1068e-02, -2.9154e-03, -7.7446e-04, -3.0820e-02,  6.0389e-02,
         1.2655e-02, -4.1634e-02,  2.1472e-02, -6.2175e-02, -5.3562e-03,
        -3.1084e-02,  2.1053e-02,  6.6292e-02,  4.4087e-03, -9.8898e-03,
         3.7816e-02, -2.8352e-02])

ModuleNotFoundError: No module named 'hgnn_model'

In [26]:
count =0 
for aid, idx in id2idx.items():
    print(f"aid: {aid}, idx: {idx}, clip[aid]: {clip_data[aid]}")
    count+=1
    if count==5: 
        break

aid: 0804691001, idx: 0, clip[aid]: tensor([-2.7453e-03,  2.1458e-02, -1.1507e-03,  4.8934e-02,  5.0829e-02,
        -8.8418e-02, -5.5898e-02,  2.7377e-02,  6.0033e-03,  5.5205e-02,
        -2.3292e-02,  1.3512e-02, -1.5547e-02, -4.0378e-02,  4.1804e-02,
         1.5855e-03, -1.3557e-01, -4.6019e-03,  7.8842e-03,  1.1295e-02,
        -2.8956e-02, -2.6889e-02, -5.8524e-03,  4.6037e-02, -7.6074e-03,
        -7.5044e-02,  3.2624e-02,  3.1794e-02, -3.4085e-02,  1.6035e-02,
         4.4593e-03,  7.0416e-02,  4.3510e-02,  2.2921e-02, -2.2443e-02,
         2.6625e-03, -2.8765e-02,  5.0812e-02, -2.8906e-02, -2.9266e-02,
        -2.7010e-02, -2.9344e-02,  6.1212e-02,  2.0099e-02, -2.9916e-02,
        -2.2835e-02, -5.9972e-02,  6.6185e-02, -7.6287e-02, -2.3912e-02,
        -1.0622e-02, -7.0510e-02, -6.2842e-03, -6.1542e-03, -1.8099e-02,
         4.3694e-02,  4.5749e-03,  8.9964e-03, -5.5017e-02,  3.3349e-02,
        -5.4911e-02, -4.6642e-02,  5.7501e-02,  7.9351e-02,  3.4872e-02,
         4.3267e-02,  1.4836e-02,  7.7906e-02,  7.7586e-02, -5.6749e-02,
        -4.1539e-02, -1.7063e-02,  1.2585e-02, -1.6259e-02,  3.9087e-02,
        -3.0173e-02,  6.6174e-02,  4.8325e-02, -2.4786e-02, -8.3648e-04,
        -1.2925e-04, -4.9272e-02, -1.5849e-02,  2.1610e-02,  2.6842e-02,
         4.8900e-03, -7.3754e-02,  7.9643e-03,  1.6978e-02,  4.2269e-02,
        -1.0242e-02,  1.0702e-02, -7.4660e-02, -1.0926e-02, -4.5899e-03,
         1.4817e-02,  7.3462e-02, -7.6476e-03,  2.1213e-02, -6.4920e-03,
        -1.6641e-02,  4.8402e-02, -3.1708e-03, -4.0830e-02,  8.4425e-02,
        -9.4235e-02,  4.4166e-04,  5.0460e-02, -6.3394e-02,  3.5308e-02,
        -1.2674e-01, -5.6344e-02, -2.1160e-02,  3.0355e-02, -1.7569e-02,
        -7.7199e-02,  1.7178e-02, -9.4415e-03,  4.0300e-02,  2.4611e-02,
         1.1860e-02, -6.6613e-04, -4.8614e-02, -2.4278e-02,  3.4942e-02,
        -1.5616e-02, -2.2113e-02, -2.3142e-02, -1.7050e-02, -1.9489e-02,
         4.2606e-02, -1.8692e-02,  5.8851e-03, -2.3487e-02,  3.8262e-02,
         1.5260e-02,  1.9326e-03,  5.6748e-02,  5.9637e-02, -4.0148e-02,
        -7.3289e-03, -4.3929e-02, -6.5262e-02,  5.7077e-02,  1.2185e-02,
         1.8851e-02, -2.4273e-02,  2.6942e-02,  4.1000e-02, -1.3717e-03,
        -2.8648e-02, -3.6752e-03,  2.2651e-01,  2.3346e-03,  2.9173e-03,
         1.3650e-02, -2.5834e-02,  7.1728e-03,  3.4217e-02,  2.3508e-02,
         2.3819e-02,  3.6971e-02, -3.9602e-02, -5.4182e-02,  3.4061e-02,
         8.5090e-02,  1.4415e-02,  2.2595e-02, -4.4462e-02,  5.8308e-02,
         3.0570e-02, -2.1618e-02, -6.1807e-02,  1.6878e-02, -4.4153e-02,
        -9.0503e-03,  8.4905e-02,  2.2806e-02, -2.7546e-02,  5.5770e-02,
         7.1963e-02, -2.1412e-02,  9.9291e-03,  1.8330e-02, -1.4746e-02,
        -4.4591e-02,  5.3990e-02,  1.3135e-02, -2.8582e-02, -4.5237e-02,
        -4.2880e-02,  1.6406e-01, -2.3495e-02,  3.1394e-02,  1.1616e-02,
        -2.2108e-02,  7.7265e-03,  1.9529e-02, -3.8184e-03,  3.0032e-02,
         6.8781e-02, -5.5044e-02, -4.8867e-02, -1.5029e-02, -1.3286e-02,
         3.5062e-03,  6.3618e-03,  5.4796e-02, -8.6896e-03, -3.2351e-02,
        -8.0453e-04, -4.7065e-02,  2.5498e-02,  6.9019e-03,  5.8517e-02,
        -1.7593e-04,  5.4451e-03, -2.6225e-02, -1.3507e-02, -1.0597e-02,
         6.6057e-02,  5.8124e-02,  1.0466e-02,  1.4912e-02,  2.6694e-02,
         3.6557e-03, -5.7640e-03, -3.6428e-02, -7.4979e-02,  1.7266e-02,
         3.2880e-02,  1.2725e-02, -2.9230e-02,  4.7664e-02,  2.4342e-02,
        -8.3351e-02,  1.1135e-02,  7.1508e-02,  1.6131e-02, -3.9441e-02,
         3.0579e-02,  4.7577e-02, -3.5855e-02, -2.1258e-02,  8.2841e-02,
        -4.3125e-02, -2.0135e-02,  1.1125e-02, -1.9269e-03, -5.6526e-02,
         2.6899e-02, -3.3625e-02,  6.7236e-02, -4.1538e-02, -8.8020e-02,
        -9.0591e-03,  8.5105e-03,  5.5013e-03,  5.6373e-02, -4.5022e-02,
        -8.2055e-03,  2.7910e-02,  1.1038e-02, -4.5333e-02,  1.0907e-02,
         1.0280e-02, -6.7286e-02, -1.2547e-02, -1.7199e-02, -4.0815e-03,
        -5.4289e-02, -5.3341e-02,  1.7591e-02,  1.2903e-02, -2.5394e-02,
         1.1221e-02,  7.4507e-03, -4.4489e-02,  1.6171e-02,  1.8395e-02,
        -4.4123e-02,  1.9755e-02, -3.0229e-02,  5.8019e-02,  4.6795e-03,
         9.6788e-03,  6.2902e-02,  3.9675e-02, -4.6232e-02, -3.2964e-02,
         3.8835e-02, -5.5732e-04, -1.5037e-02,  5.7539e-03, -4.8788e-02,
         6.8853e-03,  1.8319e-02, -4.9667e-02,  5.4241e-02, -3.3432e-02,
        -3.3193e-02, -7.3096e-02,  7.5726e-02,  3.8912e-02, -9.4443e-02,
         6.7351e-03,  1.8192e-03, -2.2602e-01,  6.0289e-03,  3.2529e-02,
        -9.9012e-03, -3.9571e-02,  5.2787e-02,  2.7215e-02,  4.0754e-02,
         2.5107e-02,  8.2634e-02, -8.6280e-02,  5.2803e-02, -1.4668e-02,
         2.0239e-02, -4.1749e-02, -2.9595e-02, -4.5328e-02, -9.0991e-02,
         7.7101e-03, -4.9008e-02, -2.9963e-02, -3.3761e-02, -4.1067e-02,
        -5.6913e-02, -2.1305e-02, -1.1343e-02, -2.5129e-02, -4.3343e-02,
        -1.3763e-03, -1.8744e-03, -4.2819e-02, -2.0988e-02,  1.4442e-02,
        -1.3799e-03, -2.3467e-02,  8.9153e-02, -9.7923e-03, -1.3998e-02,
        -1.9061e-02,  3.3377e-02,  5.1726e-02, -1.3303e-01, -7.0361e-02,
         3.2835e-02, -1.5424e-02,  1.2997e-03,  2.8691e-03, -3.7351e-02,
         6.3847e-02, -3.6625e-02,  6.8753e-02,  1.0164e-02,  5.7445e-02,
         7.3074e-03,  5.3546e-02,  7.1858e-02,  6.9741e-03, -7.3839e-02,
        -2.1982e-02,  5.8059e-02,  1.1431e-02,  1.1558e-01, -6.5928e-03,
         5.8417e-02, -2.2785e-02,  5.0931e-03, -3.1151e-02, -1.3456e-02,
        -1.0406e-02,  1.3347e-02, -6.3644e-03,  5.7457e-02, -4.4761e-02,
         3.7448e-04,  4.4326e-02, -4.0817e-02, -2.8926e-02,  6.4503e-03,
         6.7321e-02,  1.9995e-02, -2.4013e-02,  8.2547e-03, -1.4872e-02,
         4.3643e-02, -5.1709e-02,  2.5540e-02,  3.6810e-03,  1.2705e-02,
         4.2249e-04,  4.0244e-03,  4.9059e-02, -1.2798e-02, -4.6381e-03,
         2.8677e-02,  1.7503e-02, -3.1924e-02,  1.2226e-02, -1.6274e-02,
        -6.3899e-03,  1.5843e-02, -8.3830e-03, -7.6755e-04,  6.3517e-02,
         1.7643e-03, -1.0218e-02,  1.1026e-02, -2.8293e-02,  8.3782e-03,
         1.5829e-02, -4.1130e-02,  1.2029e-02, -4.1129e-02, -1.9574e-02,
         5.5190e-02, -1.1245e-02,  5.0901e-02, -4.3541e-02,  1.0462e-01,
         4.8852e-02, -8.0541e-03, -2.0616e-02,  4.9334e-02, -1.4064e-02,
         9.3928e-03,  2.3050e-01, -3.0065e-02,  2.9886e-02, -5.0563e-03,
        -1.0310e-02, -4.3125e-02, -9.7982e-04, -1.1484e-02,  3.2440e-02,
         1.7708e-04, -2.6316e-02, -4.7601e-02, -3.7427e-02, -5.5723e-02,
        -4.5169e-02, -5.2382e-02,  3.3328e-02,  6.5035e-02,  4.4245e-02,
        -2.4247e-02,  1.0958e-02, -3.8012e-03,  9.3687e-03, -1.0455e-02,
        -4.8623e-02, -3.7918e-02, -5.7656e-02, -2.9251e-02, -7.4467e-03,
        -2.8233e-02, -2.6011e-02, -3.3146e-02, -1.4843e-02,  2.5285e-02,
         1.2664e-02,  2.6582e-02,  4.7119e-02,  1.7997e-02,  2.0727e-02,
        -3.9826e-02, -5.0813e-02, -4.5016e-02,  1.0957e-02,  2.0329e-02,
         6.8451e-02,  6.4848e-02,  3.4018e-02,  1.4165e-02, -2.4294e-02,
         2.2664e-03,  3.1082e-02,  3.1288e-02,  4.0510e-03,  2.7570e-02,
         1.5212e-02, -5.5939e-02,  5.2566e-02, -8.3010e-02, -3.8244e-02,
        -1.3474e-01, -3.4860e-03,  3.2794e-02,  5.7016e-02, -5.8199e-04,
         5.7745e-02, -7.5090e-03, -3.4699e-02, -4.2533e-02,  6.0293e-02,
         1.8545e-02,  1.8663e-02,  8.3297e-03, -8.1823e-02, -3.8485e-02,
        -5.9899e-02,  5.6424e-02,  5.8983e-02,  5.4906e-03,  1.8318e-02,
        -1.6655e-02,  3.9289e-03])
aid: 0557485004, idx: 1, clip[aid]: tensor([-1.6471e-02,  4.1504e-02, -1.6870e-02, -4.2060e-02, -3.3945e-03,
        -5.9345e-02, -2.3343e-03, -5.0782e-03,  2.4068e-02,  2.7350e-02,
         1.5867e-02, -2.5241e-02, -3.7676e-02, -2.0380e-02, -5.6646e-02,
         4.6072e-03, -2.5181e-02, -5.2729e-02,  5.9786e-02, -4.4293e-02,
        -2.4017e-02, -6.3551e-02, -5.4132e-03,  4.8615e-03,  2.4630e-02,
         3.4734e-02,  8.9564e-03, -1.1010e-02,  7.1698e-02, -1.4937e-02,
        -2.4979e-03,  2.7213e-02,  3.6260e-02, -5.4114e-03, -1.5289e-02,
         8.6700e-03, -1.3020e-02,  4.7336e-02,  2.3679e-02,  4.5636e-03,
         2.7841e-02,  2.3077e-02,  1.2004e-01,  1.8523e-02, -6.3448e-02,
        -3.3442e-02, -3.4410e-03,  1.5529e-02, -1.3761e-02, -1.0819e-02,
         3.7086e-02,  6.3061e-02,  3.1354e-03,  1.6183e-02, -1.0097e-01,
         8.7123e-03, -3.7557e-02,  3.5195e-03,  7.3977e-02,  6.1249e-02,
        -3.9470e-02,  4.8241e-02,  4.7359e-02, -5.1096e-02, -2.7338e-02,
        -3.0591e-03,  2.2058e-02, -8.2955e-02,  9.6917e-03, -6.8137e-03,
        -4.3427e-02,  6.0343e-02,  3.1077e-02,  2.3790e-02, -6.8535e-03,
        -2.9499e-02,  3.6719e-03,  4.1165e-02, -4.5981e-02, -1.7830e-02,
        -5.1809e-02, -1.3755e-02, -2.8375e-04, -7.4560e-03,  5.7243e-02,
         4.4950e-02,  2.9220e-02,  1.3046e-02,  2.0799e-02,  3.8567e-02,
        -8.6715e-03,  7.4733e-03, -2.8601e-02, -2.1928e-02,  5.0478e-02,
         1.8516e-02, -9.5547e-03,  5.8435e-02, -4.8732e-02,  7.7880e-02,
        -1.7897e-02,  7.8297e-03,  7.4751e-03, -3.3525e-02,  3.9004e-02,
        -1.5792e-02,  6.8365e-02, -1.8659e-02,  1.2003e-02, -3.8566e-02,
         7.0022e-02, -2.7847e-02,  1.2350e-02,  1.6957e-02,  5.1423e-02,
        -5.0374e-03, -1.4106e-02,  2.4324e-02, -1.0614e-02,  7.6780e-03,
         1.7846e-02,  4.0849e-02,  2.9566e-02,  4.8240e-02, -1.4154e-02,
        -4.0270e-02,  2.4621e-02,  3.1743e-03, -6.3324e-03,  4.9683e-02,
         1.6714e-02, -3.3627e-02,  2.5423e-02, -3.1854e-04, -1.3745e-02,
         1.6442e-02,  2.5393e-02,  2.4385e-02,  2.6412e-02,  8.5163e-03,
         1.4635e-02,  2.3865e-02,  8.0753e-03,  2.4789e-02,  2.6322e-02,
         2.6172e-02, -2.2030e-02,  3.3611e-02,  7.2338e-04,  8.3549e-02,
         8.7415e-03,  5.8548e-02,  3.5774e-01, -2.3305e-02, -1.6354e-02,
         3.7301e-02, -4.7815e-03, -1.5854e-02,  5.1517e-03,  2.4931e-03,
        -1.8579e-02,  2.2143e-02, -5.0695e-02,  2.9384e-02,  2.1800e-02,
        -3.7573e-02, -9.6626e-03, -9.0840e-02,  7.9272e-02,  4.5318e-02,
        -3.2044e-02,  5.6958e-03,  1.3529e-02, -5.7607e-02, -3.8768e-02,
         2.5270e-02, -1.4678e-02,  3.3008e-02, -1.7462e-02, -2.1470e-02,
        -3.7065e-02,  1.1580e-04,  5.9870e-03,  1.2295e-02, -1.1024e-02,
         3.4171e-02,  4.9841e-02,  1.5736e-02, -5.9500e-03,  1.1057e-03,
        -2.1597e-02,  1.1120e-01,  2.3343e-03,  2.0806e-03, -1.2159e-02,
         1.4300e-02, -3.1449e-02,  1.6683e-02,  1.1436e-02, -2.2800e-03,
         2.4792e-02, -9.2575e-02, -2.9040e-02, -3.1085e-02,  4.6100e-02,
         2.9748e-03, -1.1323e-03, -6.8961e-02, -2.3069e-02, -6.9205e-02,
         1.7892e-02, -3.2409e-02, -2.7494e-02, -1.9996e-03, -4.5347e-02,
         5.4505e-02, -6.2715e-02,  1.9423e-02,  3.2365e-02,  8.4735e-02,
         3.8522e-02,  7.3978e-03, -1.2259e-02, -2.0781e-02,  3.1106e-02,
        -8.9868e-03, -1.6344e-02,  3.5981e-02, -2.6173e-02, -2.0659e-02,
         5.0383e-02, -1.5296e-02,  7.3187e-03, -1.1008e-02, -4.3978e-02,
        -2.6619e-02, -2.1239e-02,  2.1815e-02, -1.7871e-02,  1.3681e-02,
         1.9883e-03,  1.1108e-02,  9.8691e-03,  5.8535e-02,  6.7495e-02,
        -8.9482e-03, -1.6966e-02, -1.2619e-02,  4.8321e-02, -4.5943e-02,
        -3.3936e-02,  1.9541e-02, -8.6035e-03, -4.3452e-02, -3.0192e-02,
        -2.3486e-02, -2.7103e-02,  1.8579e-02,  7.3760e-02,  2.6349e-03,
         1.3088e-02, -4.7086e-02,  2.3983e-02, -3.1244e-02, -1.6355e-02,
        -3.1568e-02, -5.4022e-03,  3.3853e-04, -9.6318e-02, -3.6111e-02,
         5.1370e-02,  4.1063e-03,  5.9807e-02, -2.0608e-02,  1.4391e-02,
        -3.1891e-02,  2.2560e-02, -3.8095e-02,  3.7302e-03, -2.7738e-02,
         2.3901e-02,  9.6888e-03,  1.4591e-02,  3.1316e-02,  5.8835e-02,
        -1.7108e-02,  1.3963e-03, -5.9809e-02, -1.6002e-02, -3.0719e-02,
        -1.0695e-03,  1.3106e-02, -1.5701e-02,  1.0709e-02, -6.0700e-02,
        -3.3148e-02, -1.6988e-02,  5.5051e-02, -3.3595e-03, -2.8141e-02,
         1.2853e-01, -5.7523e-02, -2.2490e-02, -1.4968e-02,  2.4419e-02,
         7.6853e-02, -4.8610e-03, -3.5753e-01, -4.6984e-02, -3.1088e-02,
        -2.8303e-02, -4.5343e-02,  2.3982e-03,  1.8712e-02,  3.8235e-02,
         4.7923e-02, -3.8971e-02, -1.3013e-02,  2.5031e-02, -1.1472e-02,
        -2.5635e-03, -5.8643e-04, -2.5179e-02,  3.4907e-03, -1.5025e-01,
        -1.0195e-02, -6.4946e-02, -1.5259e-02, -3.0997e-02, -2.6767e-02,
        -1.9551e-02, -1.2630e-02,  1.1357e-02, -2.1975e-04, -4.7296e-03,
        -6.1165e-03,  8.3375e-03, -3.8029e-02, -2.5718e-02,  5.2391e-02,
         1.5604e-02, -4.6129e-02,  5.8282e-03,  6.8369e-03, -2.5118e-02,
        -5.3960e-02,  9.6314e-03,  1.3447e-02, -1.6189e-01,  1.1531e-02,
         6.0353e-02, -1.7839e-02, -1.1544e-02, -4.2178e-02, -2.0348e-02,
         9.6672e-04, -7.4483e-03,  4.9440e-02,  2.5394e-02,  3.1723e-02,
        -8.2439e-03,  5.7007e-02,  1.3337e-03,  2.9289e-03, -3.9266e-02,
         1.3473e-02, -5.3950e-02,  2.6947e-02,  7.7603e-03, -2.7638e-02,
         2.6539e-02, -6.3533e-02,  1.5652e-02, -1.9459e-02, -8.0400e-03,
         9.8765e-02, -2.2381e-02, -2.6356e-02, -2.6813e-03, -6.4029e-02,
         4.0802e-03, -3.6178e-02, -4.1968e-02, -7.3501e-03, -4.7938e-02,
         4.4731e-02, -2.3710e-02, -1.7223e-02,  4.8141e-02,  3.7738e-02,
        -2.5288e-02, -1.4875e-02,  1.7516e-02,  2.5772e-02,  1.9596e-02,
         2.0236e-02,  7.9960e-02, -2.0580e-02, -1.3061e-02,  8.0448e-03,
        -3.0877e-02,  1.7741e-02, -7.8590e-02,  2.4378e-02,  9.3045e-03,
        -8.9800e-03, -3.0842e-03, -1.0365e-02,  1.2257e-02,  4.7472e-02,
         9.3993e-03,  1.6729e-02,  3.9958e-02,  1.9979e-02,  1.7015e-02,
         3.2062e-02, -2.5384e-02, -4.3361e-02, -3.5903e-02, -4.1968e-02,
        -2.9883e-02, -1.4361e-02, -4.1949e-02, -3.6378e-02,  7.2490e-02,
         3.0464e-02,  3.3566e-02, -2.4240e-02, -3.3596e-03, -3.3821e-02,
        -4.2617e-02, -2.0267e-02,  4.0096e-03,  1.4012e-02, -7.0304e-02,
         5.8064e-02,  2.3120e-02,  1.4706e-02,  1.4688e-02,  7.1308e-03,
         2.3635e-02, -9.3370e-03, -3.1815e-02,  5.2113e-02, -3.7425e-03,
         9.5868e-03, -5.0854e-02,  4.4600e-02,  1.4281e-02,  6.7584e-03,
         5.3712e-02,  5.8250e-02,  5.7273e-02, -3.0046e-03,  1.7925e-02,
        -7.5427e-02,  6.7864e-02,  1.1229e-02,  3.3917e-03,  3.0658e-02,
         4.3558e-02, -2.0999e-02, -7.0540e-02, -2.6638e-02,  3.1681e-02,
        -1.7265e-02, -1.5347e-02, -4.2519e-02,  3.7083e-02, -6.1819e-02,
         3.8332e-02, -4.7684e-02, -1.3836e-02, -2.5588e-02,  3.1238e-03,
         1.2382e-01,  5.2402e-02, -1.8399e-03, -4.7052e-03, -3.3447e-02,
        -2.5599e-02,  2.6870e-03, -1.9120e-02,  5.6813e-02, -6.5083e-03,
        -7.2848e-03, -4.7339e-02, -5.3244e-02, -1.3074e-02, -8.5403e-03,
        -1.9244e-01, -1.7275e-02,  3.3113e-03,  2.8385e-02, -1.5008e-02,
         9.0400e-02, -2.0188e-02,  3.0255e-02, -8.6857e-02,  2.8371e-03,
        -8.8374e-03,  2.6058e-02,  2.8473e-02, -7.5259e-02,  5.6247e-02,
        -4.5330e-03,  4.2167e-02,  4.6135e-02, -6.2753e-03,  2.0394e-02,
         1.2434e-02, -4.6464e-02])
aid: 0817736004, idx: 2, clip[aid]: tensor([-1.4357e-02,  4.7101e-03, -4.4386e-02, -1.1615e-02,  7.9895e-03,
        -2.6594e-02, -4.1906e-02, -3.2006e-02, -1.1262e-02,  1.3354e-01,
        -3.0455e-02, -1.6447e-02, -4.3282e-02,  2.5682e-02,  3.1986e-02,
         1.7073e-02, -1.5455e-01, -7.5762e-03, -1.3674e-02, -1.7081e-02,
        -4.7478e-02, -4.1856e-02, -1.1514e-02, -1.8628e-02, -5.8079e-02,
        -5.3900e-02, -1.9541e-03, -9.4012e-03, -1.6938e-02,  4.4894e-02,
         3.1181e-02,  6.8220e-02,  4.2560e-02, -1.5844e-03,  1.8559e-02,
        -5.6102e-02, -3.2757e-02,  1.4730e-02,  1.2055e-02,  3.8086e-02,
         1.0886e-02, -1.2240e-02,  7.0170e-02,  4.1408e-02, -8.0276e-02,
        -5.5560e-02, -6.4153e-02, -1.6000e-02, -5.1504e-03, -3.8229e-02,
         5.0470e-02, -4.7638e-02, -6.1472e-02,  4.1424e-02,  3.0004e-02,
         3.6887e-02, -2.0152e-02,  7.7794e-02,  8.5863e-02, -3.8847e-02,
        -6.6718e-02, -3.7264e-02, -3.9690e-03,  3.6475e-02, -1.6885e-02,
         1.2384e-03,  5.9620e-02,  5.1594e-02,  2.0355e-02,  4.2112e-02,
        -4.4509e-02,  6.8198e-03,  1.8142e-02,  4.3900e-02,  1.0841e-03,
        -2.1820e-02,  5.9546e-02,  3.4584e-02, -2.3295e-02, -4.4835e-02,
         1.9182e-02, -6.4545e-02, -2.3060e-03, -1.7019e-02, -1.3878e-02,
         4.3452e-02, -2.9249e-02,  6.6969e-03, -1.2371e-02, -3.4274e-02,
         4.4405e-03, -2.6321e-02, -6.4505e-02, -1.3064e-02, -6.9264e-03,
         6.2409e-02,  9.0737e-02,  3.2446e-02,  1.4905e-02, -1.6251e-02,
        -3.7207e-02,  8.3836e-02,  2.2734e-02, -3.7170e-02,  2.3400e-02,
        -1.2708e-02,  2.8652e-02,  7.0691e-03, -4.4983e-03, -9.9020e-03,
        -9.0399e-02, -9.3783e-02, -2.3402e-02, -1.0313e-02,  5.0322e-03,
        -3.6235e-02, -1.7882e-02,  4.8266e-02,  2.7780e-02,  1.3309e-02,
        -3.3782e-02,  2.6954e-02,  5.6137e-02,  2.4850e-02,  4.2562e-02,
         1.9454e-02,  2.2492e-02,  2.1628e-02, -4.6175e-02,  2.4183e-02,
         3.8968e-02, -4.3122e-02, -4.0893e-02,  8.8358e-03, -3.9318e-03,
         6.5540e-02, -3.9212e-03, -2.1255e-02,  9.7259e-03,  8.3572e-02,
        -5.0515e-02,  8.0389e-03, -6.9242e-02,  4.4621e-02,  2.6793e-03,
         6.1429e-02,  5.3866e-03, -1.5796e-02,  2.7908e-02,  3.1835e-02,
        -2.8636e-03,  3.5158e-03,  1.6290e-01, -2.8630e-02, -1.6234e-02,
         9.5018e-03,  4.8838e-02,  1.3907e-02,  7.8219e-02, -3.1875e-02,
        -2.1414e-02,  3.8436e-03, -8.1253e-02,  1.0246e-02,  1.0693e-02,
         1.1083e-02,  2.6428e-02, -1.9053e-02,  8.4981e-02,  5.2700e-02,
         1.0607e-02, -1.3052e-04, -2.2741e-02, -2.7500e-02,  1.4202e-02,
        -1.1078e-01,  1.0576e-01, -1.1210e-02, -1.0464e-01,  3.2532e-03,
        -4.1439e-03, -1.0353e-02, -3.8360e-02,  2.6325e-02, -3.6293e-02,
         6.8029e-02,  1.5960e-01, -8.3588e-03,  4.8723e-02, -3.7134e-02,
        -1.9130e-02,  6.4942e-02,  2.0098e-02,  4.4804e-03, -6.1055e-02,
         3.0263e-03,  7.6717e-02,  8.8256e-02, -1.1692e-02,  2.5178e-02,
         6.7203e-02,  3.3814e-02, -3.6467e-02, -5.1836e-02, -4.5930e-03,
        -8.5191e-03, -2.4062e-03, -5.6548e-02, -2.6454e-02, -1.0821e-01,
        -5.6784e-02,  1.7220e-02, -4.4785e-02, -1.0024e-02,  1.0704e-02,
         8.4534e-03, -2.5725e-02,  2.0515e-03, -1.2963e-02, -8.6728e-02,
         5.7849e-03, -2.3552e-02, -8.7760e-03,  2.0085e-02,  5.0884e-02,
         1.5385e-03, -2.2877e-02, -6.1968e-02, -5.6965e-02, -5.6732e-02,
        -8.5690e-03,  4.1937e-02, -1.1986e-02,  3.7021e-02,  7.2202e-02,
        -3.7130e-02, -2.4224e-02,  6.1848e-03,  3.4392e-02, -5.5995e-02,
        -1.7673e-02,  7.1037e-02,  1.7644e-02,  3.7468e-02,  7.5352e-02,
        -3.2002e-03, -7.2856e-02, -5.2278e-02, -3.8645e-02, -6.4772e-02,
         1.8546e-02, -2.2536e-02, -5.0126e-02, -4.4522e-02, -5.8248e-02,
        -5.9415e-02, -3.9249e-02,  4.9526e-03,  2.5225e-02, -4.2317e-02,
         3.3357e-02, -3.8758e-02,  2.1768e-02, -4.1701e-02,  2.8140e-02,
         1.6135e-02, -1.9432e-02,  1.4175e-02, -6.4762e-02, -2.4185e-02,
        -4.3140e-02, -7.1738e-02, -4.6211e-03,  2.3798e-02, -3.0686e-02,
         4.2835e-03, -6.9294e-03, -5.6271e-02,  2.8654e-03, -3.9473e-02,
         2.7445e-02,  4.3028e-02, -1.3529e-02,  3.1126e-02,  1.5380e-02,
         5.3579e-02, -5.5335e-02,  5.5885e-03, -9.0017e-03, -3.5484e-02,
         4.5959e-02,  1.5911e-02, -4.1660e-02, -2.5559e-03, -9.2976e-03,
        -4.2198e-02, -3.6050e-02, -5.2932e-02,  2.2856e-02, -2.9635e-02,
         5.6867e-02, -1.8290e-02,  4.8235e-02,  5.1934e-02, -3.0743e-02,
        -1.5751e-02, -3.9829e-03, -1.6327e-01, -5.1340e-02,  1.2831e-03,
        -4.3043e-02, -2.0874e-02,  5.5983e-04, -2.9231e-02,  1.3612e-01,
         3.7895e-02,  3.6994e-02, -4.0226e-02,  3.8454e-02,  1.5099e-02,
        -6.7797e-03, -1.4366e-02,  2.9383e-02,  2.4266e-02, -1.4958e-01,
         2.0205e-02,  7.9442e-02, -4.5438e-03, -8.1351e-02,  2.9185e-02,
        -3.0814e-02, -2.9367e-02,  4.7647e-02,  3.0419e-02,  2.8214e-03,

In [28]:
data_test = pd.read_csv("../data/test.csv")
data_test

,t_dat,customer_id,article_id,event_type
0,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,884319008,purchase
1,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,858052007,click
2,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,921226001,purchase
3,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,832282001,click
4,2020-08-14,00009d946eec3ea54add5ba56d5210ea898def4b46c685...,706016001,purchase
...,...,...,...,...
184753,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,742916003,click
184754,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,761696002,click
184755,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,796600003,click
184756,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,582480024,click
184757,2020-08-14,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,751288001,click